# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.cache/wt [current_project]
set_property parent.project_path C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/new/ALU.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/imports/new/TENHz_Counter2.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/imports/new/IRTransmitterSM2.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/new/Processor.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/new/Timer.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/new/ROM.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/new/RAM.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/imports/new/New_Top_Wrapper.v
  C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/sources_1/new/Top_Wrapper.v
}
read_xdc C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/constrs_1/imports/new/IRTransmitterSMXDC.xdc
set_property used_in_implementation false [get_files C:/DSL4/Micrprocessor/Microprocessor/Microprocessor.srcs/constrs_1/imports/new/IRTransmitterSMXDC.xdc]

synth_design -top Top_Wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Top_Wrapper.dcp
catch { report_utilization -file Top_Wrapper_utilization_synth.rpt -pb Top_Wrapper_utilization_synth.pb }
